commit: c4317b0c

runtime Summary:
AST Parsed     : 17878/17878 (100.00%)
Positive Passed: 17625/17878 (98.58%)
tasks/coverage/test262/test/language/expressions/assignment/fn-name-lhs-cover.js
codegen error: Test262Error: descriptor value should be ; object value should be 

tasks/coverage/test262/test/language/expressions/async-arrow-function/forbidden-ext/b1/async-arrow-function-forbidden-ext-direct-access-prop-arguments.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/expressions/async-arrow-function/forbidden-ext/b1/async-arrow-function-forbidden-ext-direct-access-prop-caller.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/expressions/async-arrow-function/prototype.js
transform error: Test262Error: Expected SameValue(«function () { [native code] }», «[object AsyncFunction]») to be true

tasks/coverage/test262/test/language/expressions/async-function/forbidden-ext/b1/async-func-expr-named-forbidden-ext-direct-access-prop-arguments.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/expressions/async-function/forbidden-ext/b1/async-func-expr-named-forbidden-ext-direct-access-prop-caller.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/expressions/async-function/forbidden-ext/b1/async-func-expr-nameless-forbidden-ext-direct-access-prop-arguments.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/expressions/async-function/forbidden-ext/b1/async-func-expr-nameless-forbidden-ext-direct-access-prop-caller.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/expressions/async-function/named-reassign-fn-name-in-body-in-arrow.js
transform error: Test262Error: Expected SameValue(«1», «function BindingIdentifier() {
		return _BindingIdentifier.apply(this, arguments);
	}») to be true

tasks/coverage/test262/test/language/expressions/async-function/named-reassign-fn-name-in-body-in-eval.js
transform error: Test262Error: Expected SameValue(«1», «function BindingIdentifier() {
		return _BindingIdentifier.apply(this, arguments);
	}») to be true

tasks/coverage/test262/test/language/expressions/async-function/named-reassign-fn-name-in-body.js
transform error: Test262Error: Expected SameValue(«1», «function BindingIdentifier() {
		return _BindingIdentifier.apply(this, arguments);
	}») to be true

tasks/coverage/test262/test/language/expressions/async-function/named-strict-error-reassign-fn-name-in-body-in-arrow.js
transform error: Test262Error: Expected SameValue(«0», «1») to be true

tasks/coverage/test262/test/language/expressions/async-function/named-strict-error-reassign-fn-name-in-body-in-eval.js
transform error: Test262Error: Expected SameValue(«0», «1») to be true

tasks/coverage/test262/test/language/expressions/async-function/named-strict-error-reassign-fn-name-in-body.js
transform error: Test262Error: Expected SameValue(«0», «1») to be true

tasks/coverage/test262/test/language/expressions/async-generator/default-proto.js
transform error: Test262Error: fn.prototype is undefined Expected SameValue(«[object Object]», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/async-generator/forbidden-ext/b1/async-gen-func-expr-forbidden-ext-direct-access-prop-arguments.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/expressions/async-generator/forbidden-ext/b1/async-gen-func-expr-forbidden-ext-direct-access-prop-caller.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/expressions/async-generator/forbidden-ext/b1/async-gen-named-func-expr-forbidden-ext-direct-access-prop-arguments.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/expressions/async-generator/forbidden-ext/b1/async-gen-named-func-expr-forbidden-ext-direct-access-prop-caller.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-no-strict-reassign-fn-name-in-body-in-arrow.js
transform error: Test262Error: Expected SameValue(«1», «function BindingIdentifier() {
		return _BindingIdentifier.apply(this, arguments);
	}») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-no-strict-reassign-fn-name-in-body-in-eval.js
transform error: Test262Error: Expected SameValue(«1», «function BindingIdentifier() {
		return _BindingIdentifier.apply(this, arguments);
	}») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-no-strict-reassign-fn-name-in-body.js
transform error: Test262Error: Expected SameValue(«1», «function BindingIdentifier() {
		return _BindingIdentifier.apply(this, arguments);
	}») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-strict-error-reassign-fn-name-in-body-in-arrow.js
transform error: Test262Error: Expected SameValue(«0», «1») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-strict-error-reassign-fn-name-in-body-in-eval.js
transform error: Test262Error: Expected SameValue(«0», «1») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-strict-error-reassign-fn-name-in-body.js
transform error: Test262Error: Expected SameValue(«0», «1») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-yield-star-async-next.js
transform error: Test262Error: Expected SameValue(«"get next done (1)"», «"get next value (1)"») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-yield-star-async-return.js
transform error: Test262Error: Expected SameValue(«"get return"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-yield-star-async-throw.js
transform error: Test262Error: Expected SameValue(«"get throw"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-yield-star-next-call-done-get-abrupt.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/async-generator/named-yield-star-next-call-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-yield-star-next-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-yield-star-next-non-object-ignores-then.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/async-generator/named-yield-star-next-then-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-yield-star-next-then-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/async-generator/named-yield-star-sync-throw.js
transform error: throw-arg-1

tasks/coverage/test262/test/language/expressions/async-generator/yield-star-async-next.js
transform error: Test262Error: Expected SameValue(«"get next done (1)"», «"get next value (1)"») to be true

tasks/coverage/test262/test/language/expressions/async-generator/yield-star-async-return.js
transform error: Test262Error: Expected SameValue(«"get return"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/async-generator/yield-star-async-throw.js
transform error: Test262Error: Expected SameValue(«"get throw"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/async-generator/yield-star-next-call-done-get-abrupt.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/async-generator/yield-star-next-call-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/async-generator/yield-star-next-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/async-generator/yield-star-next-non-object-ignores-then.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/async-generator/yield-star-next-then-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/async-generator/yield-star-next-then-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/async-generator/yield-star-sync-throw.js
transform error: throw-arg-1

tasks/coverage/test262/test/language/expressions/await/await-monkey-patched-promise.js
transform error: Test262Error: Monkey-patched "then" on native promises should not be called. Expected SameValue(«1», «0») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method/yield-star-async-next.js
transform error: Test262Error: Expected SameValue(«"get next done (1)"», «"get next value (1)"») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method/yield-star-async-return.js
transform error: Test262Error: Expected SameValue(«"get return"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method/yield-star-async-throw.js
transform error: Test262Error: Expected SameValue(«"get throw"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method/yield-star-next-call-done-get-abrupt.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/class/async-gen-method/yield-star-next-call-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method/yield-star-next-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method/yield-star-next-non-object-ignores-then.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/class/async-gen-method/yield-star-next-then-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method/yield-star-next-then-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method/yield-star-sync-throw.js
transform error: throw-arg-1

tasks/coverage/test262/test/language/expressions/class/async-gen-method-static/yield-star-async-next.js
transform error: Test262Error: Expected SameValue(«"get next done (1)"», «"get next value (1)"») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method-static/yield-star-async-return.js
transform error: Test262Error: Expected SameValue(«"get return"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method-static/yield-star-async-throw.js
transform error: Test262Error: Expected SameValue(«"get throw"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method-static/yield-star-next-call-done-get-abrupt.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/class/async-gen-method-static/yield-star-next-call-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method-static/yield-star-next-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method-static/yield-star-next-non-object-ignores-then.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/class/async-gen-method-static/yield-star-next-then-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method-static/yield-star-next-then-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/async-gen-method-static/yield-star-sync-throw.js
transform error: throw-arg-1

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method/yield-star-async-next.js
transform error: Test262Error: Expected SameValue(«"get next done (1)"», «"get next value (1)"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method/yield-star-async-return.js
transform error: Test262Error: Expected SameValue(«"get return"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method/yield-star-async-throw.js
transform error: Test262Error: Expected SameValue(«"get throw"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method/yield-star-next-call-done-get-abrupt.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method/yield-star-next-call-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method/yield-star-next-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method/yield-star-next-non-object-ignores-then.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method/yield-star-next-then-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method/yield-star-next-then-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method/yield-star-sync-throw.js
transform error: throw-arg-1

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method-static/yield-star-async-next.js
transform error: Test262Error: Expected SameValue(«"get next done (1)"», «"get next value (1)"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method-static/yield-star-async-return.js
transform error: Test262Error: Expected SameValue(«"get return"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method-static/yield-star-async-throw.js
transform error: Test262Error: Expected SameValue(«"get throw"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method-static/yield-star-next-call-done-get-abrupt.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method-static/yield-star-next-call-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method-static/yield-star-next-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method-static/yield-star-next-non-object-ignores-then.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method-static/yield-star-next-then-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method-static/yield-star-next-then-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/class/elements/async-gen-private-method-static/yield-star-sync-throw.js
transform error: throw-arg-1

tasks/coverage/test262/test/language/expressions/class/elements/class-name-static-initializer-anonymous.js
transform error: Test262Error: Expected SameValue(«"_Class"», «"C"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/class-name-static-initializer-default-export.js
transform error: Test262Error: Expected SameValue(«"_Class"», «"default"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/computed-name-toprimitive-symbol.js
transform error: TypeError: Cannot convert a Symbol value to a string

tasks/coverage/test262/test/language/expressions/class/elements/evaluation-error/computed-name-toprimitive-err.js
transform error: Test262Error: Expected a Test262Error to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/expressions/class/elements/evaluation-error/computed-name-toprimitive-returns-noncallable.js
transform error: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/expressions/class/elements/evaluation-error/computed-name-toprimitive-returns-nonobject.js
transform error: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/expressions/class/elements/evaluation-error/computed-name-tostring-err.js
transform error: Test262Error: Expected a Test262Error to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/expressions/class/elements/evaluation-error/computed-name-valueof-err.js
transform error: Test262Error: Expected a Test262Error to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/expressions/class/elements/private-async-generator-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/private-async-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/private-generator-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/private-methods/prod-private-async-generator.js
transform error: Test262Error: function name inside constructor Expected SameValue(«"_m"», «"#m"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/private-methods/prod-private-async-method.js
transform error: Test262Error: function name inside constructor Expected SameValue(«"_m"», «"#m"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/private-methods/prod-private-generator.js
transform error: Test262Error: function name inside constructor Expected SameValue(«"_m"», «"#m"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/private-methods/prod-private-method.js
transform error: Test262Error: function name inside constructor Expected SameValue(«"_m"», «"#m"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/private-static-async-generator-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/private-static-async-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/private-static-generator-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/private-static-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/static-field-anonymous-function-name.js
transform error: Test262Error: Expected SameValue(«"_"», «"#field"») to be true

tasks/coverage/test262/test/language/expressions/class/elements/static-field-init-with-this.js
transform error: Test262Error: Expected SameValue(«"undefinedtest"», «"test262test"») to be true

tasks/coverage/test262/test/language/expressions/class/heritage-async-arrow-function.js
transform error: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/expressions/compound-assignment/left-hand-side-private-reference-accessor-property-add.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «3») to be true

tasks/coverage/test262/test/language/expressions/compound-assignment/left-hand-side-private-reference-accessor-property-bitand.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «0») to be true

tasks/coverage/test262/test/language/expressions/compound-assignment/left-hand-side-private-reference-accessor-property-bitor.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «15») to be true

tasks/coverage/test262/test/language/expressions/compound-assignment/left-hand-side-private-reference-accessor-property-bitxor.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «257») to be true

tasks/coverage/test262/test/language/expressions/compound-assignment/left-hand-side-private-reference-accessor-property-div.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «0.5») to be true

tasks/coverage/test262/test/language/expressions/compound-assignment/left-hand-side-private-reference-accessor-property-exp.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «1000») to be true

tasks/coverage/test262/test/language/expressions/compound-assignment/left-hand-side-private-reference-accessor-property-lshift.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «96») to be true

tasks/coverage/test262/test/language/expressions/compound-assignment/left-hand-side-private-reference-accessor-property-mod.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «1») to be true

tasks/coverage/test262/test/language/expressions/compound-assignment/left-hand-side-private-reference-accessor-property-mult.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «6») to be true

tasks/coverage/test262/test/language/expressions/compound-assignment/left-hand-side-private-reference-accessor-property-rshift.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «3») to be true

tasks/coverage/test262/test/language/expressions/compound-assignment/left-hand-side-private-reference-accessor-property-srshift.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «3») to be true

tasks/coverage/test262/test/language/expressions/compound-assignment/left-hand-side-private-reference-accessor-property-sub.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «1») to be true

tasks/coverage/test262/test/language/expressions/does-not-equals/S11.9.2_A7.8.js
minify error: Test262Error: #7: (1 != {valueOf: function() {throw "error"}, toString: function() {return 1}}) throw "error"

tasks/coverage/test262/test/language/expressions/exponentiation/bigint-negative-exponent-throws.js
transform error: Test262Error: (-1n) ** -1n throws RangeError Expected a RangeError but got a TypeError

tasks/coverage/test262/test/language/expressions/in/private-field-rhs-non-object.js
transform error: Test262Error: Expected SameValue(«null», «null») to be false

tasks/coverage/test262/test/language/expressions/logical-assignment/left-hand-side-private-reference-accessor-property-and.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «false») to be true

tasks/coverage/test262/test/language/expressions/logical-assignment/left-hand-side-private-reference-accessor-property-nullish.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «1») to be true

tasks/coverage/test262/test/language/expressions/logical-assignment/left-hand-side-private-reference-accessor-property-or.js
transform error: Test262Error: The expression should evaluate to the result Expected SameValue(«undefined», «true») to be true

tasks/coverage/test262/test/language/expressions/logical-assignment/left-hand-side-private-reference-method-and.js
transform error: Test262Error: PutValue throws when storing the result in a method private reference Expected a TypeError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/expressions/logical-assignment/left-hand-side-private-reference-method-short-circuit-nullish.js
transform error: Test262Error: The right-hand side should not be evaluated

tasks/coverage/test262/test/language/expressions/logical-assignment/left-hand-side-private-reference-method-short-circuit-or.js
transform error: Test262Error: The right-hand side should not be evaluated

tasks/coverage/test262/test/language/expressions/object/__proto__-permitted-dup-shorthand.js
codegen error: Test262Error: Expected SameValue(«[object Object]», «2») to be true

tasks/coverage/test262/test/language/expressions/object/dstr/object-rest-proxy-gopd-not-called-on-excluded-keys.js
transform error: Test262Error: Actual [excludedString, 0, includedString, 1, Symbol(included_symbol)] and expected [Symbol(included_symbol), includedString, 1] should have the same contents. 

tasks/coverage/test262/test/language/expressions/object/method-definition/async-gen-yield-star-async-next.js
transform error: Test262Error: Expected SameValue(«"get next done (1)"», «"get next value (1)"») to be true

tasks/coverage/test262/test/language/expressions/object/method-definition/async-gen-yield-star-async-return.js
transform error: Test262Error: Expected SameValue(«"get return"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/object/method-definition/async-gen-yield-star-async-throw.js
transform error: Test262Error: Expected SameValue(«"get throw"», «"get next"») to be true

tasks/coverage/test262/test/language/expressions/object/method-definition/async-gen-yield-star-next-call-done-get-abrupt.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/object/method-definition/async-gen-yield-star-next-call-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/object/method-definition/async-gen-yield-star-next-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/object/method-definition/async-gen-yield-star-next-non-object-ignores-then.js
transform error: Timed out.

tasks/coverage/test262/test/language/expressions/object/method-definition/async-gen-yield-star-next-then-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/object/method-definition/async-gen-yield-star-next-then-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/expressions/object/method-definition/async-gen-yield-star-sync-throw.js
transform error: throw-arg-1

tasks/coverage/test262/test/language/expressions/object/object-spread-proxy-get-not-called-on-dontenum-keys.js
transform error: Test262Error: Actual [dontEnumString, 0, enumerableString, 1, Symbol(dont_enum_symbol), Symbol(enumerable_symbol)] and expected [Symbol(dont_enum_symbol), dontEnumString, 0, Symbol(enumerable_symbol), enumerableString, 1] should have the same contents. 

tasks/coverage/test262/test/language/expressions/object/object-spread-proxy-no-excluded-keys.js
transform error: TypeError: Cannot read properties of undefined (reading 'enumerable')

tasks/coverage/test262/test/language/expressions/object/object-spread-proxy-ownkeys-returned-keys-order.js
transform error: TypeError: Cannot read properties of undefined (reading 'enumerable')

tasks/coverage/test262/test/language/expressions/unsigned-right-shift/S11.7.3_A2.2_T1.js
minify error: Test262Error: #8.2: -4 >>> {valueOf: function() {return {}}, toString: function() {return {}}} throw TypeError. Actual: ReferenceError: e is not defined

tasks/coverage/test262/test/language/literals/regexp/u-surrogate-pairs-atom-escape-decimal.js
codegen error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/statements/async-function/forbidden-ext/b1/async-func-decl-forbidden-ext-direct-access-prop-arguments.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/statements/async-function/forbidden-ext/b1/async-func-decl-forbidden-ext-direct-access-prop-caller.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/statements/async-generator/forbidden-ext/b1/async-gen-func-decl-forbidden-ext-direct-access-prop-arguments.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/statements/async-generator/forbidden-ext/b1/async-gen-func-decl-forbidden-ext-direct-access-prop-caller.js
transform error: Test262Error: Expected SameValue(«true», «false») to be true

tasks/coverage/test262/test/language/statements/async-generator/return-undefined-implicit-and-explicit.js
transform error: Test262Error: Actual [tick 1, tick 2, g1 ret, g2 ret, g3 ret, g4 ret] and expected [tick 1, g1 ret, g2 ret, tick 2, g3 ret, g4 ret] should have the same contents. Ticks for implicit and explicit return undefined

tasks/coverage/test262/test/language/statements/async-generator/yield-star-async-from-sync-iterator-inaccessible.js
transform error: TypeError: Cannot convert undefined or null to object

tasks/coverage/test262/test/language/statements/async-generator/yield-star-async-next.js
transform error: Test262Error: Expected SameValue(«"get next done (1)"», «"get next value (1)"») to be true

tasks/coverage/test262/test/language/statements/async-generator/yield-star-async-return.js
transform error: Test262Error: Expected SameValue(«"get return"», «"get next"») to be true

tasks/coverage/test262/test/language/statements/async-generator/yield-star-async-throw.js
transform error: Test262Error: Expected SameValue(«"get throw"», «"get next"») to be true

tasks/coverage/test262/test/language/statements/async-generator/yield-star-next-call-done-get-abrupt.js
transform error: Timed out.

tasks/coverage/test262/test/language/statements/async-generator/yield-star-next-call-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/async-generator/yield-star-next-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/async-generator/yield-star-next-non-object-ignores-then.js
transform error: Timed out.

tasks/coverage/test262/test/language/statements/async-generator/yield-star-next-then-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/async-generator/yield-star-next-then-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/async-generator/yield-star-normal-notdone-iter-value-throws.js
transform error: Timed out.

tasks/coverage/test262/test/language/statements/async-generator/yield-star-promise-not-unwrapped.js
transform error: Test262Error: .throw should not be accessed

tasks/coverage/test262/test/language/statements/async-generator/yield-star-return-notdone-iter-value-throws.js
transform error: Timed out.

tasks/coverage/test262/test/language/statements/async-generator/yield-star-return-then-getter-ticks.js
transform error: Test262Error: Actual [start, get return, tick 1, get then, tick 2, tick 3] and expected [start, tick 1, get then, tick 2, get return, get then, tick 3] should have the same contents. Ticks for return with thenable getter

tasks/coverage/test262/test/language/statements/async-generator/yield-star-sync-throw.js
transform error: throw-arg-1

tasks/coverage/test262/test/language/statements/async-generator/yield-star-throw-notdone-iter-value-throws.js
transform error: Timed out.

tasks/coverage/test262/test/language/statements/class/async-gen-method/yield-star-async-next.js
transform error: Test262Error: Expected SameValue(«"get next done (1)"», «"get next value (1)"») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method/yield-star-async-return.js
transform error: Test262Error: Expected SameValue(«"get return"», «"get next"») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method/yield-star-async-throw.js
transform error: Test262Error: Expected SameValue(«"get throw"», «"get next"») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method/yield-star-next-call-done-get-abrupt.js
transform error: Timed out.

tasks/coverage/test262/test/language/statements/class/async-gen-method/yield-star-next-call-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method/yield-star-next-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method/yield-star-next-non-object-ignores-then.js
transform error: Timed out.

tasks/coverage/test262/test/language/statements/class/async-gen-method/yield-star-next-then-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method/yield-star-next-then-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method/yield-star-sync-throw.js
transform error: throw-arg-1

tasks/coverage/test262/test/language/statements/class/async-gen-method-static/yield-star-async-next.js
transform error: Test262Error: Expected SameValue(«"get next done (1)"», «"get next value (1)"») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method-static/yield-star-async-return.js
transform error: Test262Error: Expected SameValue(«"get return"», «"get next"») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method-static/yield-star-async-throw.js
transform error: Test262Error: Expected SameValue(«"get throw"», «"get next"») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method-static/yield-star-next-call-done-get-abrupt.js
transform error: Timed out.

tasks/coverage/test262/test/language/statements/class/async-gen-method-static/yield-star-next-call-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method-static/yield-star-next-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method-static/yield-star-next-non-object-ignores-then.js
transform error: Timed out.

tasks/coverage/test262/test/language/statements/class/async-gen-method-static/yield-star-next-then-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method-static/yield-star-next-then-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/async-gen-method-static/yield-star-sync-throw.js
transform error: throw-arg-1

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method/yield-star-async-next.js
transform error: Test262Error: Expected SameValue(«"get next done (1)"», «"get next value (1)"») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method/yield-star-async-return.js
transform error: Test262Error: Expected SameValue(«"get return"», «"get next"») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method/yield-star-async-throw.js
transform error: Test262Error: Expected SameValue(«"get throw"», «"get next"») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method/yield-star-next-call-done-get-abrupt.js
transform error: Timed out.

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method/yield-star-next-call-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method/yield-star-next-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method/yield-star-next-non-object-ignores-then.js
transform error: Timed out.

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method/yield-star-next-then-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method/yield-star-next-then-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method/yield-star-sync-throw.js
transform error: throw-arg-1

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method-static/yield-star-async-next.js
transform error: Test262Error: Expected SameValue(«"get next done (1)"», «"get next value (1)"») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method-static/yield-star-async-return.js
transform error: Test262Error: Expected SameValue(«"get return"», «"get next"») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method-static/yield-star-async-throw.js
transform error: Test262Error: Expected SameValue(«"get throw"», «"get next"») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method-static/yield-star-next-call-done-get-abrupt.js
transform error: Timed out.

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method-static/yield-star-next-call-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method-static/yield-star-next-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method-static/yield-star-next-non-object-ignores-then.js
transform error: Timed out.

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method-static/yield-star-next-then-get-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method-static/yield-star-next-then-returns-abrupt.js
transform error: Test262Error: reject reason Expected SameValue(«TypeError: The iterator does not provide a 'throw' method.», «[object Object]») to be true

tasks/coverage/test262/test/language/statements/class/elements/async-gen-private-method-static/yield-star-sync-throw.js
transform error: throw-arg-1

tasks/coverage/test262/test/language/statements/class/elements/class-field-on-frozen-objects.js
transform error: Test262Error: Frozen objects can't be changed Expected a TypeError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/statements/class/elements/computed-name-toprimitive-symbol.js
transform error: TypeError: Cannot convert a Symbol value to a string

tasks/coverage/test262/test/language/statements/class/elements/evaluation-error/computed-name-toprimitive-err.js
transform error: Test262Error: Expected a Test262Error to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/statements/class/elements/evaluation-error/computed-name-toprimitive-returns-noncallable.js
transform error: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/statements/class/elements/evaluation-error/computed-name-toprimitive-returns-nonobject.js
transform error: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/statements/class/elements/evaluation-error/computed-name-tostring-err.js
transform error: Test262Error: Expected a Test262Error to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/statements/class/elements/evaluation-error/computed-name-valueof-err.js
transform error: Test262Error: Expected a Test262Error to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/statements/class/elements/private-async-generator-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/statements/class/elements/private-async-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/statements/class/elements/private-generator-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/statements/class/elements/private-methods/prod-private-async-generator.js
transform error: Test262Error: function name inside constructor Expected SameValue(«"_m"», «"#m"») to be true

tasks/coverage/test262/test/language/statements/class/elements/private-methods/prod-private-async-method.js
transform error: Test262Error: function name inside constructor Expected SameValue(«"_m"», «"#m"») to be true

tasks/coverage/test262/test/language/statements/class/elements/private-methods/prod-private-generator.js
transform error: Test262Error: function name inside constructor Expected SameValue(«"_m"», «"#m"») to be true

tasks/coverage/test262/test/language/statements/class/elements/private-methods/prod-private-method.js
transform error: Test262Error: function name inside constructor Expected SameValue(«"_m"», «"#m"») to be true

tasks/coverage/test262/test/language/statements/class/elements/private-static-async-generator-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/statements/class/elements/private-static-async-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/statements/class/elements/private-static-generator-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/statements/class/elements/private-static-method-name.js
transform error: Test262Error: Expected SameValue(«"_method"», «"#method"») to be true

tasks/coverage/test262/test/language/statements/class/elements/static-field-anonymous-function-name.js
transform error: Test262Error: Expected SameValue(«"_"», «"#field"») to be true

tasks/coverage/test262/test/language/statements/class/elements/static-field-init-with-this.js
transform error: Test262Error: Expected SameValue(«"undefinedtest"», «"test262test"») to be true

tasks/coverage/test262/test/language/statements/class/static-init-expr-new-target.js
transform error: SyntaxError: new.target expression is not allowed here

tasks/coverage/test262/test/language/statements/class/subclass/superclass-async-function.js
transform error: TypeError: Cannot redefine property: prototype

tasks/coverage/test262/test/language/statements/class/subclass/superclass-async-generator-function.js
transform error: Test262Error: Expected a TypeError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/statements/for-await-of/async-from-sync-iterator-continuation-abrupt-completion-get-constructor.js
transform error: Test262Error: Actual [start, tick 1, catch, tick 2] and expected [start, tick 1, tick 2, catch] should have the same contents. 

tasks/coverage/test262/test/language/statements/for-await-of/async-func-decl-dstr-array-elem-init-yield-ident-valid.js
transform error: Test262Error: Expected SameValue(«undefined», «4») to be true

tasks/coverage/test262/test/language/statements/for-await-of/async-func-decl-dstr-array-elem-nested-array-yield-ident-valid.js
transform error: Test262Error: Expected SameValue(«undefined», «22») to be true

tasks/coverage/test262/test/language/statements/for-await-of/async-func-decl-dstr-array-elem-nested-obj-yield-ident-valid.js
transform error: Test262Error: Expected SameValue(«undefined», «2») to be true

tasks/coverage/test262/test/language/statements/for-await-of/async-func-decl-dstr-array-elem-target-yield-valid.js
transform error: Test262Error: Expected SameValue(«undefined», «33») to be true

tasks/coverage/test262/test/language/statements/for-await-of/async-func-decl-dstr-array-rest-nested-array-yield-ident-valid.js
transform error: Test262Error: Expected SameValue(«undefined», «86») to be true

tasks/coverage/test262/test/language/statements/for-await-of/async-func-decl-dstr-array-rest-nested-obj-yield-ident-valid.js
transform error: Test262Error: Expected SameValue(«undefined», «2») to be true

tasks/coverage/test262/test/language/statements/for-await-of/async-func-decl-dstr-array-rest-yield-ident-valid.js
transform error: TypeError: Cannot read properties of undefined (reading 'length')

tasks/coverage/test262/test/language/statements/for-await-of/async-func-decl-dstr-obj-id-init-yield-ident-valid.js
transform error: Test262Error: Expected SameValue(«undefined», «3») to be true

tasks/coverage/test262/test/language/statements/for-await-of/async-func-decl-dstr-obj-prop-elem-init-yield-ident-valid.js
transform error: Test262Error: Expected SameValue(«undefined», «4») to be true

tasks/coverage/test262/test/language/statements/for-await-of/async-func-decl-dstr-obj-prop-elem-target-yield-ident-valid.js
transform error: Test262Error: Expected SameValue(«undefined», «23») to be true

tasks/coverage/test262/test/language/statements/for-await-of/async-func-decl-dstr-obj-prop-nested-array-yield-ident-valid.js
transform error: Test262Error: Expected SameValue(«undefined», «22») to be true

tasks/coverage/test262/test/language/statements/for-await-of/async-func-decl-dstr-obj-prop-nested-obj-yield-ident-valid.js
transform error: Test262Error: Expected SameValue(«undefined», «2») to be true

tasks/coverage/test262/test/language/statements/for-await-of/ticks-with-async-iter-resolved-promise-and-constructor-lookup-two.js
transform error: Test262Error: Actual [pre, constructor, constructor, tick 1, loop, constructor, constructor, tick 2, post] and expected [pre, constructor, tick 1, loop, constructor, tick 2, post] should have the same contents. Ticks and constructor lookups

tasks/coverage/test262/test/language/statements/for-await-of/ticks-with-async-iter-resolved-promise-and-constructor-lookup.js
transform error: Test262Error: Actual [pre, constructor, tick 1, loop, constructor, tick 2, post] and expected [pre, tick 1, loop, tick 2, post] should have the same contents. Ticks and constructor lookups

tasks/coverage/test262/test/language/statements/for-await-of/ticks-with-sync-iter-resolved-promise-and-constructor-lookup.js
transform error: Test262Error: Actual [pre, constructor, constructor, constructor, constructor, tick 1, tick 2, loop, constructor, constructor, constructor, tick 3, tick 4, post] and expected [pre, constructor, constructor, tick 1, tick 2, loop, constructor, tick 3, tick 4, post] should have the same contents. Ticks and constructor lookups

tasks/coverage/test262/test/language/statements/for-in/scope-body-lex-open.js
minify error: Test262Error: Expected a ReferenceError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/statements/for-in/scope-head-lex-close.js
minify error: Test262Error: Expected a ReferenceError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/statements/for-in/scope-head-lex-open.js
minify error: Test262Error: Expected a ReferenceError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/statements/for-of/scope-body-lex-open.js
minify error: Test262Error: Expected a ReferenceError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/statements/for-of/scope-head-lex-close.js
minify error: Test262Error: Expected a ReferenceError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/statements/for-of/scope-head-lex-open.js
minify error: Test262Error: Expected a ReferenceError to be thrown but no exception was thrown at all

tasks/coverage/test262/test/language/statements/for-of/string-astral-truncated.js
codegen error: Test262Error: Expected SameValue(«"\\"», «"\\ud801"») to be true

